rm(list = ls())
library(stringr)
library(dplyr)
library(RcppEigen)
library(RcppArmadillo)
library(Rcpp)
source("Shuffle.R")
source("Train_SA.R")
source("Kfold.R")
source("Validate.R")
source("Draw.R")
source("None_zero_idx_same.R")
source("Delete.R")
source("Ins_right.R")
source("Main_new_C.R")
source("Preprocessing.R")
source("Add_synthesis.R")
source("Add_synthesis_2.R")
source("Main_synthetic.R")
source("GetpBad.R")

args=commandArgs(T)
input<-args[1]
seed<-as.integer(args[2])
traits<-as.integer(args[3])
K<-as.integer(args[4])
obj_best<-as.numeric(args[5])
Iter<-as.integer(args[6])

result<-Main_new_C(input, seed, traits, K, obj_best, Iter)
